Import Libraries

In [2]:
import cv2
import sys

XML files

In [4]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')

In [5]:
jim_halpert = cv2.imread("jim.jpeg",1)
print("Jim size" , type(jim_halpert))
print("Jim shape",jim_halpert.shape)
print(jim_halpert)

Jim size <class 'numpy.ndarray'>
Jim shape (463, 717, 3)
[[[112 112 119]
  [114 114 121]
  [117 117 124]
  ...
  [ 31  48  84]
  [ 31  48  84]
  [ 31  48  84]]

 [[109 109 115]
  [110 110 117]
  [112 112 119]
  ...
  [ 19  37  73]
  [ 19  37  73]
  [ 19  37  73]]

 [[109 109 115]
  [110 110 117]
  [112 112 119]
  ...
  [ 17  34  70]
  [ 17  34  70]
  [ 17  34  70]]

 ...

 [[ 21  17  20]
  [ 21  17  20]
  [ 21  17  20]
  ...
  [ 20  24  28]
  [ 19  22  26]
  [ 19  22  26]]

 [[ 22  19  21]
  [ 22  19  21]
  [ 22  19  21]
  ...
  [ 25  28  32]
  [ 24  27  31]
  [ 24  27  31]]

 [[ 33  30  33]
  [ 33  30  33]
  [ 33  30  33]
  ...
  [ 32  35  39]
  [ 31  34  38]
  [ 31  34  38]]]


Detects faces

In [17]:
faces = face_cascade.detectMultiScale(jim_halpert,scaleFactor=1.1,minNeighbors=3)

In [ ]:
for (x,y,w,h) in faces:
    print("x",x)
    print("y",y)
    print("w",w)
    print("h",h)
    cv2.rectangle(jim_halpert,(x,y),(x+w,y+h),(0,255,0),1)

In [ ]:
while cv2.waitKey(1) == -1:
    cv2.imshow("Jimothy",jim_halpert)

In [ ]:
cv2.destroyAllWindows()

Using Webcam

In [ ]:
webcam = cv2.VideoCapture(0)

In [11]:
while True:
    ret , frame = webcam.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray,1.1,minNeighbors=4)
    
    for(x,y,w,z) in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
    cv2.imshow('webcam',frame)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
webcam.release()

In [12]:
cv2.destroyAllWindows()